version: 2.0

jobs:
  python-2.7:
    docker:
      - image: circleci/python:2.7.16
    working_directory: ~/rubrik-modules-for-ansible
    environment:
      ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/collections
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pylint requests python-dateutil pytz coverage pytest-cov pytest-mock tox pep8 autopep8 rubrik_cdm paramiko PyYAML Jinja2 httplib2 six voluptuous isort lazy-object-proxy wrapt docutils rstcheck pathspec yamllint
            sudo apt-get install -y man
      - run:
          name: Clone and Setup Ansible Dev Tools
          command: |
            git clone https://github.com/ansible/ansible.git ~/ansible
            source ~/ansible/hacking/env-setup
            mkdir -p ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            cp -a ~/rubrik-modules-for-ansible/rubrikinc/cdm/. ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            ls ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            rm -f ~/.ansible/collections/ansible_collections/rubrikinc/cdm/docs/template.md
            rm -f ~/.ansible/collections/ansible_collections/rubrikinc/cdm/docs/create_documentation_block.py
            rm -f ~/.ansible/collections/ansible_collections/rubrikinc/cdm/docs/rubrik_module_template.py
            rm -f ~/.ansible/collections/ansible_collections/rubrikinc/cdm/docs/README.md
            rm -f ~/.ansible/collections/ansible_collections/rubrikinc/cdm/docs/SUMMARY.md
      - run:
          name: Execute Ansible Sanity Test
          command: |
            cd ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            ~/ansible/bin/ansible-test sanity --test compile --python 2.7

  python-3.5:
    docker:
      - image: circleci/python:3.5.7
        environment:
          PYTHONPATH: /home/circleci/.ansible/collections

    working_directory: ~/rubrik-modules-for-ansible
    environment:
      ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/collections
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pylint requests python-dateutil pytz coverage pytest-cov pytest-mock tox pep8 autopep8 rubrik_cdm paramiko PyYAML Jinja2 httplib2 six voluptuous isort lazy-object-proxy wrapt docutils rstcheck pathspec yamllint --progress-bar off
            sudo apt-get install -y man
      - run:
          name: Clone and Setup Ansible Dev Tools
          command: |
            git clone --single-branch --branch stable-2.9 https://github.com/ansible/ansible.git ~/ansible
            source ~/ansible/hacking/env-setup
            mkdir -p ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            chown -R $USER:$USER ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            cp -a ~/rubrik-modules-for-ansible/rubrikinc/cdm/. ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            rm -f ~/.ansible/collections/ansible_collections/rubrikinc/cdm/docs/{template.md,create_documentation_block.py,create_documentation_block.py,rubrik_module_template.py,README.md,SUMMARY.md}
            python collection_dev.py --action update_path --platform circleci

      - run:
          name: Execute Ansible Sanity Test
          command: |
            cd ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            ~/ansible/bin/ansible-test sanity --skip-test shebang
      - run:
          name: Execute Unit Tests
          command: |
            sudo pip install ansible --progress-bar off
            pytest ~/.ansible/collections/ansible_collections/rubrikinc/cdm/tests/unit

  python-3.6:
    docker:
      - image: circleci/python:3.6.9
        environment:
          PYTHONPATH: /home/circleci/.ansible/collections
    working_directory: ~/rubrik-modules-for-ansible
    environment:
      ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/collections
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pylint requests python-dateutil pytz coverage pytest-cov pytest-mock tox pep8 autopep8 rubrik_cdm paramiko PyYAML Jinja2 httplib2 six voluptuous 'isort<5.0' lazy-object-proxy wrapt docutils rstcheck pathspec yamllint --progress-bar off
            sudo apt-get install -y man
      - run:
          name: Clone and Setup Ansible Dev Tools
          command: |
            git clone https://github.com/ansible/ansible.git ~/ansible
            source ~/ansible/hacking/env-setup
            mkdir -p ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            chown -R $USER:$USER ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            cp -a ~/rubrik-modules-for-ansible/rubrikinc/cdm/. ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            rm -f ~/.ansible/collections/ansible_collections/rubrikinc/cdm/docs/{template.md,create_documentation_block.py,create_documentation_block.py,rubrik_module_template.py,README.md,SUMMARY.md}
            python collection_dev.py --action update_path --platform circleci

      - run:
          name: Execute Ansible Sanity Test
          command: |
            cd ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            ~/ansible/bin/ansible-test sanity --skip-test shebang
      - run:
          name: Execute Unit Tests
          command: |
            sudo pip install ansible --progress-bar off
            pytest ~/.ansible/collections/ansible_collections/rubrikinc/cdm/tests/unit

  python-3.7:
    docker:
      - image: circleci/python:3.7.4
        environment:
          PYTHONPATH: /home/circleci/.ansible/collections
    working_directory: ~/rubrik-modules-for-ansible
    environment:
      ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/collections
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pylint requests python-dateutil pytz coverage pytest-cov pytest-mock tox pep8 autopep8 rubrik_cdm paramiko PyYAML Jinja2 httplib2 six voluptuous 'isort<5.0' lazy-object-proxy wrapt docutils rstcheck pathspec yamllint --progress-bar off
            sudo apt-get install -y man
      - run:
          name: Clone and Setup Ansible Dev Tools
          command: |
            git clone https://github.com/ansible/ansible.git ~/ansible
            source ~/ansible/hacking/env-setup
            mkdir -p ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            chown -R $USER:$USER ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            cp -a ~/rubrik-modules-for-ansible/rubrikinc/cdm/. ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            rm -f ~/.ansible/collections/ansible_collections/rubrikinc/cdm/docs/{template.md,create_documentation_block.py,create_documentation_block.py,rubrik_module_template.py,README.md,SUMMARY.md}
            python collection_dev.py --action update_path --platform circleci

      - run:
          name: Execute Ansible Sanity Test
          command: |
            cd ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            ~/ansible/bin/ansible-test sanity --skip-test shebang
      - run:
          name: Execute Unit Tests
          command: |
            sudo pip install ansible --progress-bar off
            pytest ~/.ansible/collections/ansible_collections/rubrikinc/cdm/tests/unit

  python-3.8:
    docker:
      - image: circleci/python:3.8.0b4
        environment:
          PYTHONPATH: /home/circleci/.ansible/collections
    working_directory: ~/rubrik-modules-for-ansible
    environment:
      ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/collections
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pylint requests python-dateutil pytz coverage pytest-cov pytest-mock tox pep8 autopep8 rubrik_cdm paramiko PyYAML Jinja2 httplib2 six voluptuous isort lazy-object-proxy wrapt docutils rstcheck pathspec yamllint --progress-bar off
            sudo apt-get install -y man
      - run:
          name: Clone and Setup Ansible Dev Tools
          command: |
            git clone https://github.com/ansible/ansible.git ~/ansible
            source ~/ansible/hacking/env-setup
            mkdir -p ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            chown -R $USER:$USER ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            cp -a ~/rubrik-modules-for-ansible/rubrikinc/cdm/. ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            rm -f ~/.ansible/collections/ansible_collections/rubrikinc/cdm/docs/{template.md,create_documentation_block.py,create_documentation_block.py,rubrik_module_template.py,README.md,SUMMARY.md}
            python collection_dev.py --action update_path --platform circleci

      - run:
          name: Execute Ansible Sanity Test
          command: |
            cd ~/.ansible/collections/ansible_collections/rubrikinc/cdm
            ~/ansible/bin/ansible-test sanity --skip-test shebang
      - run:
          name: Execute Unit Tests
          command: |
            sudo pip install ansible --progress-bar off
            pytest ~/.ansible/collections/ansible_collections/rubrikinc/cdm/tests/unit

workflows:
  version: 2
  build:
    jobs:
      - python-2.7
      - python-3.5
      - python-3.6
      - python-3.7
      #- python-3.8
