### requried
# this can be a company/brand or product namespace under which all content lives
namespace: rubrikinc
# the designation of this specific collection
name: cdm
# semantic versioning compliant version designation
version: "1.0.6"
readme: README.md
# a list of the collection's content authors: 'Full Name <email> (http://site) @nicks:irc/im/site#channel'
authors: Rubrik Build

### optional but strongly advised
# short summary of the collection
description: Ansible Modules that utilize the Rubrik RESTful API to manage the Rubrik Cloud Data Management Platform.
# a valid SPDX license identifier https://spdx.org/licenses/
license: MIT
# list of keywords you want to associate the collection with for indexing/search systems
tags: cloud

### urls
# url of originating SCM repository
repository: https://github.com/rubrikinc/rubrik-modules-for-ansible
# url to online docs
documentation: https://rubrik.gitbook.io/rubrik-modules-for-ansible/
# homepage of the collection/project
homepage: https://build.rubrik.com/tooling-integrations/ansible/
# issue tracker url
issues: https://github.com/rubrikinc/rubrik-modules-for-ansible/issues
